# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8693c5fbee19cf9a5bc0f87d8dfcd02831415517b635b9769518f0b211debc69454ee28f0e5a68a894053d4d0657b22e5c43b995d70ca0d870d794f5fc0b962

test:
  secret_key_base: 47cc0c40eb71208e55603892436f76fa2bd0f671e3cd5b3cf4e0db61d7dc1e9053d4b027de504998e8bf1e0f889201524cd724f725531f2f3d34e0f78907b9b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
